version: '3.8'

services:
  frontend:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:frontend-${IMAGE_TAG}
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["npm", "start"]
    
  backend:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:backend-${IMAGE_TAG}
    ports:
      - "8080:8080"
    command: ["python3", "app.py"]
    depends_on:
      - frontend
      