version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["npm", "start"]
    
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["python3", "app.py"]
    depends_on:
      - frontend
